# Generated by Django 3.2 on 2021-06-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Middle_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Gender', models.TextField(max_length=25)),
                ('Blood_group', models.CharField(max_length=25)),
                ('Genotype', models.TextField()),
                ('Vaccination_history', models.TextField(max_length=250)),
                ('images', models.ImageField(upload_to='', verbose_name='images')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hospital', models.CharField(blank=True, choices=[('hosp1', 'Hosp1'), ('hosp2', 'Hosp2')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hospital', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Gender', models.TextField(max_length=25)),
                ('Email_address', models.EmailField(max_length=250)),
                ('Password', models.TextField()),
                ('Phone_number', models.IntegerField()),
                ('images', models.ImageField(upload_to='', verbose_name='images')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KidVacc.parent')),
            ],
        ),
    ]
