# Generated by Django 3.2 on 2021-06-24 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KidVacc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Gender', models.TextField(max_length=25)),
                ('Email_address', models.EmailField(max_length=250)),
                ('Password', models.TextField()),
                ('Phone_number', models.IntegerField()),
                ('images', models.ImageField(upload_to='', verbose_name='images')),
            ],
        ),
        migrations.DeleteModel(
            name='parent_details',
        ),
        migrations.RenameField(
            model_name='child_details',
            old_name='Fname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='child_details',
            old_name='Lname',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='child_details',
            old_name='Mname',
            new_name='Middle_name',
        ),
        migrations.RemoveField(
            model_name='child_details',
            name='Weight',
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KidVacc.user'),
        ),
    ]
