# Generated by Django 3.2 on 2021-06-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='child_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Mname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Gender', models.TextField(max_length=25)),
                ('Weight', models.CharField(max_length=30)),
                ('Blood_group', models.CharField(max_length=25)),
                ('Genotype', models.TextField()),
                ('Vaccination_history', models.TextField(max_length=250)),
                ('images', models.ImageField(upload_to='', verbose_name='images')),
            ],
        ),
        migrations.CreateModel(
            name='hospital_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hospital', models.CharField(blank=True, choices=[('hosp1', 'Hosp1'), ('hosp2', 'Hosp2')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hospital', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='parent_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Gender', models.TextField(max_length=25)),
                ('Email_address', models.EmailField(max_length=250)),
                ('Phone_number', models.IntegerField()),
                ('images', models.ImageField(upload_to='', verbose_name='images')),
            ],
        ),
    ]
