# Generated by Django 3.2.4 on 2021-07-11 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_type', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=30)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('child_age_range', models.CharField(choices=[('0-6MONTHS', '0-6MONTHS'), ('7-12MONTHS', '7-12MONTHS'), ('12-24MONTHS', '12-24MONTHS')], default='0-6MONTHS', max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=100)),
                ('Last_name', models.CharField(blank=True, max_length=100)),
                ('Gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=25)),
                ('Email_address', models.EmailField(max_length=250, null=True)),
                ('Phone_number', models.IntegerField(null=True)),
                ('images', models.ImageField(null=True, upload_to='images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('hospital_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_details', to='KidVacc.hospital_type')),
                ('vaccines', models.ManyToManyField(to='KidVacc.Vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Middle_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=25)),
                ('Date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('Blood_group', models.CharField(max_length=25)),
                ('Genotype', models.TextField()),
                ('Vaccination_history', models.TextField(max_length=250)),
                ('images', models.ImageField(upload_to='', verbose_name='images')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='KidVacc.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='KidVacc.child')),
            ],
        ),
    ]
