# Generated by Django 3.2 on 2021-07-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVacc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='Gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=25),
        ),
    ]
