# Generated by Django 3.2 on 2021-07-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVacc', '0002_alter_parent_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=25),
        ),
    ]
