# Generated by Django 3.2.4 on 2021-07-03 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KidVacc', '0003_auto_20210625_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='child',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital_details',
            name='address',
            field=models.CharField(default='address', max_length=1024, verbose_name='Address line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
