# Generated by Django 3.2.4 on 2021-07-09 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KidVacc', '0004_auto_20210703_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_type',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='Password',
        ),
        migrations.AddField(
            model_name='hospital_type',
            name='hospital_type',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=30),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='Email_address',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='First_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Gender',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
