# Generated by Django 3.2 on 2021-07-09 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KidVacc', '0004_parent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='Password',
        ),
        migrations.AlterField(
            model_name='parent',
            name='Email_address',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='First_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Gender',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='images',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
    ]
