# Generated by Django 3.2 on 2021-07-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVacc', '0005_auto_20210709_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='Phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
