# Generated by Django 3.2 on 2021-07-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVacc', '0006_auto_20210709_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_type',
            name='hospital_type',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital_type',
            name='hospital',
            field=models.CharField(blank=True, choices=[('private', 'private'), ('public', 'public')], max_length=100),
        ),
    ]
