# Generated by Django 3.2 on 2021-07-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KidVacc', '0007_auto_20210709_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_type',
            name='hospital',
        ),
    ]
